#!/usr/bin/env php
<?php 
require_once 'vendor/autoload.php';

$birthDate = "1977-11-16";
$days = new \IDEA\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n";

?>
